### ISSUE TITLE
Making "Peek" more useful

### ISSUE THREAD

**Issue by leejoramo-d51** [lydell/LinkHints#61]
I am really enjoying LinkHints. 

One of the biggest usability issues is when the Hints are too jammed together such as with a set of pagination links. The Peek Mode via Ctrl-P is useful, but still often obscures the links too much. 

I am trying this change to the CSS. In addition to opacity, it moves the Hints up a little to reveal the Links. So far I like this change, but I know it would need lots of testing to make sure their are not new problems.

```css
.peek .hint:not(.hasMatchedChars):not(.highlighted) {
  opacity: 0.2;
  margin-top:-1em;
}
```
